// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: v3/xresloader.proto

#include "v3/xresloader.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace org {
namespace xresloader {
}  // namespace xresloader
}  // namespace org
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_v3_2fxresloader_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_v3_2fxresloader_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_v3_2fxresloader_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_v3_2fxresloader_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_v3_2fxresloader_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023v3/xresloader.proto\022\016org.xresloader\032 g"
  "oogle/protobuf/descriptor.proto:7\n\020file_"
  "description\022\034.google.protobuf.FileOption"
  "s\030\351\007 \001(\t:9\n\017msg_description\022\037.google.pro"
  "tobuf.MessageOptions\030\351\007 \001(\t:A\n\027msg_requi"
  "re_mapping_all\022\037.google.protobuf.Message"
  "Options\030\363\007 \001(\010:7\n\rmsg_separator\022\037.google"
  ".protobuf.MessageOptions\030\364\007 \001(\t:0\n\010verif"
  "ier\022\035.google.protobuf.FieldOptions\030\351\007 \001("
  "\t:9\n\021field_description\022\035.google.protobuf"
  ".FieldOptions\030\363\007 \001(\t:3\n\013field_alias\022\035.go"
  "ogle.protobuf.FieldOptions\030\364\007 \001(\t:3\n\013fie"
  "ld_ratio\022\035.google.protobuf.FieldOptions\030"
  "\365\007 \001(\005:7\n\017field_separator\022\035.google.proto"
  "buf.FieldOptions\030\366\007 \001(\t:6\n\016field_require"
  "d\022\035.google.protobuf.FieldOptions\030\367\007 \001(\010:"
  "2\n\nfield_tags\022\035.google.protobuf.FieldOpt"
  "ions\030\370\007 \001(\t:9\n\021oneof_description\022\035.googl"
  "e.protobuf.OneofOptions\030\351\007 \001(\t:7\n\017oneof_"
  "separator\022\035.google.protobuf.OneofOptions"
  "\030\352\007 \001(\t:7\n\020enum_description\022\034.google.pro"
  "tobuf.EnumOptions\030\351\007 \001(\t:=\n\021enumv_descri"
  "ption\022!.google.protobuf.EnumValueOptions"
  "\030\351\007 \001(\t:6\n\nenum_alias\022!.google.protobuf."
  "EnumValueOptions\030\352\007 \001(\tb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_v3_2fxresloader_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_v3_2fxresloader_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_v3_2fxresloader_2eproto = {
  false, false, 991, descriptor_table_protodef_v3_2fxresloader_2eproto, "v3/xresloader.proto", 
  &descriptor_table_v3_2fxresloader_2eproto_once, descriptor_table_v3_2fxresloader_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_v3_2fxresloader_2eproto::offsets,
  file_level_metadata_v3_2fxresloader_2eproto, file_level_enum_descriptors_v3_2fxresloader_2eproto, file_level_service_descriptors_v3_2fxresloader_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_v3_2fxresloader_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_v3_2fxresloader_2eproto);
  return descriptor_table_v3_2fxresloader_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_v3_2fxresloader_2eproto(&descriptor_table_v3_2fxresloader_2eproto);
namespace org {
namespace xresloader {
const std::string file_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FileOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  file_description(kFileDescriptionFieldNumber, file_description_default);
const std::string msg_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  msg_description(kMsgDescriptionFieldNumber, msg_description_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  msg_require_mapping_all(kMsgRequireMappingAllFieldNumber, false);
const std::string msg_separator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::MessageOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  msg_separator(kMsgSeparatorFieldNumber, msg_separator_default);
const std::string verifier_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  verifier(kVerifierFieldNumber, verifier_default);
const std::string field_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_description(kFieldDescriptionFieldNumber, field_description_default);
const std::string field_alias_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_alias(kFieldAliasFieldNumber, field_alias_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< ::PROTOBUF_NAMESPACE_ID::int32 >, 5, false >
  field_ratio(kFieldRatioFieldNumber, 0);
const std::string field_separator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_separator(kFieldSeparatorFieldNumber, field_separator_default);
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::PrimitiveTypeTraits< bool >, 8, false >
  field_required(kFieldRequiredFieldNumber, false);
const std::string field_tags_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::FieldOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  field_tags(kFieldTagsFieldNumber, field_tags_default);
const std::string oneof_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  oneof_description(kOneofDescriptionFieldNumber, oneof_description_default);
const std::string oneof_separator_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::OneofOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  oneof_separator(kOneofSeparatorFieldNumber, oneof_separator_default);
const std::string enum_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  enum_description(kEnumDescriptionFieldNumber, enum_description_default);
const std::string enumv_description_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  enumv_description(kEnumvDescriptionFieldNumber, enumv_description_default);
const std::string enum_alias_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::google::protobuf::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  enum_alias(kEnumAliasFieldNumber, enum_alias_default);

// @@protoc_insertion_point(namespace_scope)
}  // namespace xresloader
}  // namespace org
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
